In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/anaconda-install/Library/include
    lib directory: C:/anaconda-install/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: x86_64
   

In [4]:
arr1 = np.arange(0,10,2)
arr2 = np.arange(0,10,2)
arr1
arr2
np.add(arr1,arr2)

array([ 0,  4,  8, 12, 16])

In [5]:
array = np.arange(0,50,5)
array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
np.isfinite(array)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
array==0

array([ True, False, False, False, False, False, False, False, False,
       False])

In [8]:
array!=0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [9]:
array=="NaN"

array([False, False, False, False, False, False, False, False, False,
       False])

In [10]:

array.real

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
array.real
np.isreal(array)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [12]:
np.iscomplex(array)

array([False, False, False, False, False, False, False, False, False,
       False])

In [13]:
np.isscalar(array)

False

In [14]:
arr1 > arr2

array([False, False, False, False, False])

In [71]:
arr1<arr2

array([False, False, False, False, False])

In [72]:
arr1 == arr2

array([ True,  True,  True,  True,  True])

In [73]:
arr1>=arr2

array([ True,  True,  True,  True,  True])

In [74]:
arr1<=arr2

array([ True,  True,  True,  True,  True])

In [75]:
arr1!=arr2

array([False, False, False, False, False])

In [76]:
arr = np.array([1,7,13,105])
arr

array([  1,   7,  13, 105])

In [77]:
arr.size

4

In [78]:
arr.itemsize

4

In [79]:
total_size = arr.size * arr.itemsize
total_size

16

In [80]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.random.rand(1)

array([0.58529445])

In [82]:
vector = np.arange(16,55)
vector

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [83]:
arr = np.arange(10,22)
arr.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [84]:
vector = np.linspace(0,10,5)
vector

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [85]:
arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
r,c = arr.shape
r

2

In [87]:
c

3